<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types.  It is used by the
| Upload class to help identify allowed file types.
|
*/

$mimes = array(	'hqx'	=>	'application/mac-binhex40',
				'cpt'	=>	'app/mac-compactpro',
				'csv'	=>	array('text/x-comma-separated-values', 'text/comma-separated-values', 'app/octet-stream', 'app/vnd.ms-excel', 'app/x-csv', 'text/x-csv', 'text/csv', 'app/csv', 'app/excel', 'app/vnd.msexcel'),
				'bin'	=>	'app/macbinary',
				'dms'	=>	'app/octet-stream',
				'lha'	=>	'app/octet-stream',
				'lzh'	=>	'app/octet-stream',
				'exe'	=>	array('app/octet-stream', 'app/x-msdownload'),
				'class'	=>	'app/octet-stream',
				'psd'	=>	'app/x-photoshop',
				'so'	=>	'app/octet-stream',
				'sea'	=>	'app/octet-stream',
				'dll'	=>	'app/octet-stream',
				'oda'	=>	'app/oda',
				'pdf'	=>	array('app/pdf', 'app/x-download'),
				'ai'	=>	'app/postscript',
				'eps'	=>	'app/postscript',
				'ps'	=>	'app/postscript',
				'smi'	=>	'app/smil',
				'smil'	=>	'app/smil',
				'mif'	=>	'app/vnd.mif',
				'xls'	=>	array('app/excel', 'app/vnd.ms-excel', 'app/msexcel'),
				'ppt'	=>	array('app/powerpoint', 'app/vnd.ms-powerpoint'),
				'wbxml'	=>	'app/wbxml',
				'wmlc'	=>	'app/wmlc',
				'dcr'	=>	'app/x-director',
				'dir'	=>	'app/x-director',
				'dxr'	=>	'app/x-director',
				'dvi'	=>	'app/x-dvi',
				'gtar'	=>	'app/x-gtar',
				'gz'	=>	'app/x-gzip',
				'php'	=>	'app/x-httpd-php',
				'php4'	=>	'app/x-httpd-php',
				'php3'	=>	'app/x-httpd-php',
				'phtml'	=>	'app/x-httpd-php',
				'phps'	=>	'app/x-httpd-php-source',
				'js'	=>	'app/x-javascript',
				'swf'	=>	'app/x-shockwave-flash',
				'sit'	=>	'app/x-stuffit',
				'tar'	=>	'app/x-tar',
				'tgz'	=>	array('app/x-tar', 'app/x-gzip-compressed'),
				'xhtml'	=>	'app/xhtml+xml',
				'xht'	=>	'app/xhtml+xml',
				'zip'	=>  array('app/x-zip', 'app/zip', 'app/x-zip-compressed'),
				'mid'	=>	'audio/midi',
				'midi'	=>	'audio/midi',
				'mpga'	=>	'audio/mpeg',
				'mp2'	=>	'audio/mpeg',
				'mp3'	=>	array('audio/mpeg', 'audio/mpg', 'audio/mpeg3', 'audio/mp3'),
				'aif'	=>	'audio/x-aiff',
				'aiff'	=>	'audio/x-aiff',
				'aifc'	=>	'audio/x-aiff',
				'ram'	=>	'audio/x-pn-realaudio',
				'rm'	=>	'audio/x-pn-realaudio',
				'rpm'	=>	'audio/x-pn-realaudio-plugin',
				'ra'	=>	'audio/x-realaudio',
				'rv'	=>	'video/vnd.rn-realvideo',
				'wav'	=>	array('audio/x-wav', 'audio/wave', 'audio/wav'),
				'bmp'	=>	array('image/bmp', 'image/x-windows-bmp'),
				'gif'	=>	'image/gif',
				'jpeg'	=>	array('image/jpeg', 'image/pjpeg'),
				'jpg'	=>	array('image/jpeg', 'image/pjpeg'),
				'jpe'	=>	array('image/jpeg', 'image/pjpeg'),
				'png'	=>	array('image/png',  'image/x-png'),
				'tiff'	=>	'image/tiff',
				'tif'	=>	'image/tiff',
				'css'	=>	'text/css',
				'html'	=>	'text/html',
				'htm'	=>	'text/html',
				'shtml'	=>	'text/html',
				'txt'	=>	'text/plain',
				'text'	=>	'text/plain',
				'log'	=>	array('text/plain', 'text/x-log'),
				'rtx'	=>	'text/richtext',
				'rtf'	=>	'text/rtf',
				'xml'	=>	'text/xml',
				'xsl'	=>	'text/xml',
				'mpeg'	=>	'video/mpeg',
				'mpg'	=>	'video/mpeg',
				'mpe'	=>	'video/mpeg',
				'qt'	=>	'video/quicktime',
				'mov'	=>	'video/quicktime',
				'avi'	=>	'video/x-msvideo',
				'movie'	=>	'video/x-sgi-movie',
				'doc'	=>	'app/msword',
				'docx'	=>	array('app/vnd.openxmlformats-officedocument.wordprocessingml.document', 'app/zip'),
				'xlsx'	=>	array('app/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'app/zip'),
				'word'	=>	array('app/msword', 'app/octet-stream'),
				'xl'	=>	'app/excel',
				'eml'	=>	'message/rfc822',
				'json' => array('app/json', 'text/json')
			);


/* End of file mimes.php */
/* Location: ./app/config/mimes.php */
